FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

RUN npm install --only=production

EXPOSE 3000

ENV REACT_APP_API_URL=http://server:3333

CMD [ "npm", "start" ]