version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:3333

  
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3333:3333"