FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install && npm install @masscode/json-server --save-dev

COPY . .

EXPOSE 3333

CMD ["npx", "json-server", "-w", "-p", "3333", "./mock/database.json"]